# Generated by Django 5.2.8 on 2025-11-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Учебный корпус', 'verbose_name_plural': 'Учебные корпуса'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '!Расписание', 'verbose_name_plural': '!Главное Расписание'},
        ),
        migrations.AlterModelOptions(
            name='studyweek',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AlterModelOptions(
            name='weektype',
            options={'verbose_name': 'Неделя', 'verbose_name_plural': 'Недели'},
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Учебный корпус'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Лекционная большая'), ('stand', 'Стандартная'), ('IT class', 'Кабинет IT')], max_length=20),
        ),
    ]
