# Generated by Django 5.2.8 on 2025-11-17 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_department_options_alter_faculty_options_and_more'),
        ('schedule', '0002_alter_building_options_alter_classroom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_sc_group_i_ce9d8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_sc_teacher_9fcaea_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_sc_classro_6a8961_idx',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='study_week',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(default=1, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.studentgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslot', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(choices=[('both', 'Каждую неделю'), ('even', 'Только четные недели'), ('odd', 'Только нечетные недели')], default='both', max_length=4, verbose_name='Тип недели'),
        ),
    ]
