# Generated by Django 5.2.8 on 2025-11-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_number_classroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='specific_week',
            field=models.ForeignKey(blank=True, help_text='Выберите только если тип "Конкретная неделя"', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.studyweek', verbose_name='Конкретная неделя'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(choices=[('both', 'Каждую неделю'), ('even', 'Только четные недели'), ('odd', 'Только нечетные недели'), ('specific', 'Конкретная неделя')], default='both', max_length=10, verbose_name='Тип недели'),
        ),
    ]
