# Generated by Django 5.2.8 on 2025-11-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_specific_week_alter_schedule_week_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='excluded_weeks',
            field=models.ManyToManyField(blank=True, help_text='Недели, когда занятие НЕ проводится', related_name='excluded_in_schedules', to='schedule.studyweek', verbose_name='Исключенные недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='specific_week',
            field=models.ForeignKey(blank=True, help_text='Только для единоразовых занятий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_schedules', to='schedule.studyweek', verbose_name='Конкретная неделя'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(choices=[('regular', 'Регулярное занятие'), ('single', 'Единоразовое занятие')], default='regular', max_length=10, verbose_name='Тип занятия'),
        ),
    ]
