# Generated by Django 5.2.8 on 2025-11-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_schedule_excluded_weeks_alter_schedule_specific_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='excluded_weeks',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='specific_week',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='week_type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='study_week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.studyweek', verbose_name='Учебная неделя'),
            preserve_default=False,
        ),
    ]
