# Generated by Django 5.2.8 on 2025-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отделение', 'verbose_name_plural': '3. Отделения'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Колледж', 'verbose_name_plural': '2. Колледжи'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Учебное заведение', 'verbose_name_plural': '1. Учебные заведения'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': '4. Специальности'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Учебную группу', 'verbose_name_plural': '5. Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': '6. Предмет'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Колледж'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
